# Generated by Django 5.1.3 on 2025-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0123_auto_20230205_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allowed_students',
            field=models.ManyToManyField(related_name='allowed_groups', to='sport.student'),
        ),
    ]
