# Generated by Django 5.1.3 on 2025-01-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0124_remove_medicalgroupreference_image_and_more'),
        ('sport', '0125_alter_group_allowed_students'),
    ]

    operations = [
    ]
