# Generated by Django 5.1.3 on 2025-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0126_group_banned_students_alter_group_allowed_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='allowed_gender',
            field=models.IntegerField(choices=[(-1, 'both'), (0, 'male'), (1, 'female')], default=-1, help_text='Select genders that are allowed to attend the trainings (works with "Allowed medical groups" filter).'),
        ),
        migrations.AlterField(
            model_name='group',
            name='allowed_medical_groups',
            field=models.ManyToManyField(blank=True, help_text='Select medical groups required to attend the trainings. If this is empty, nobody will see the training (except students in "Allowed students" list, they always see the training).', to='sport.medicalgroup'),
        ),
        migrations.AlterField(
            model_name='group',
            name='allowed_students',
            field=models.ManyToManyField(blank=True, help_text='List of students that are allowed to attend classes (in addition to "Allowed medical groups" filter).', related_name='allowed_groups', to='sport.student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='banned_students',
            field=models.ManyToManyField(blank=True, help_text='List of students that can not attend classes. The students will not see the training, and the teacher will not be able to set hours for these students.', related_name='banned_groups', to='sport.student'),
        ),
    ]
