# Generated by Django 5.1.3 on 2025-08-28 19:30

import django.db.models.deletion
import sport.models.medical_group_reference
from django.db import migrations, models


def transfer_existing_images(apps, schema_editor):
    """Transfer existing image data from MedicalGroupReference to MedicalGroupReferenceImage"""
    MedicalGroupReference = apps.get_model('sport', 'MedicalGroupReference')
    MedicalGroupReferenceImage = apps.get_model('sport', 'MedicalGroupReferenceImage')
    
    for reference in MedicalGroupReference.objects.exclude(image__isnull=True).exclude(image=''):
        # Create a new MedicalGroupReferenceImage for each existing image
        MedicalGroupReferenceImage.objects.create(
            medical_reference=reference,
            image=reference.image
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0127_alter_group_allowed_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalGroupReferenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sport.models.medical_group_reference.get_reference_path)),
                ('medical_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sport.medicalgroupreference', verbose_name='medical reference')),
            ],
            options={
                'verbose_name': 'medical group reference image',
                'verbose_name_plural': 'medical group reference images',
                'db_table': 'medical_group_reference_image',
            },
        ),
        # First create the new model, then transfer data, then remove the old field
        migrations.RunPython(transfer_existing_images),
        migrations.RemoveField(
            model_name='medicalgroupreference',
            name='image',
        ),
    ]
