# Generated by Django 5.1.3 on 2025-09-28 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0129_rename_medical_reference_medicalgroupreferenceimage_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('groups__verbose_name', 'Students'), ('groups__verbose_name', 'College'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
