# Generated by Django 5.1.3 on 2026-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0133_checkouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
