name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do you trigger this bug?
      placeholder: 1. Go to Settings > 2. Click Save > 3. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: I expected the settings to be saved successfully.

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: Instead, I got an error message.

  - type: input
    id: version
    attributes:
      label: Affected version
      placeholder: e.g., v1.3.2
