name: Technical Task
description: Internal development task
labels: [tech-task]
body:
  - type: textarea
    id: task
    attributes:
      label: Description
      placeholder: e.g. Refactor authentication logic.

  - type: textarea
    id: checklist
    attributes:
      label: Subtasks or Related Issues
      description: Use checklist or paste links to subtasks
      placeholder: |
        - [ ] Update login service
        - [ ] Link: #45
