name: sport

services:
  adminpanel:
    build:
      context: ../adminpage
      args:
        PYTHON_VERSION: 3.12
    #   Wait for postgres to startup before running server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env.test
    ports:
      - 8000:8000

  db:
    image: postgres:17.1-alpine
    restart: unless-stopped
    env_file:
      - .env.test
