name: Production deploy
on:
  workflow_dispatch:
  push:
    tags:
      - v**
jobs:
  deploy:
    name: Deploy to production server
    runs-on: [self-hosted, innosport]
    environment:
      name: production
      url: ${{ vars.DEPLOY_URL }}
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script: |
            cd "${{ secrets.DEPLOY_DIRECTORY }}"
            bash "${{ secrets.DEPLOY_SCRIPT }}" "${{ github.ref_name }}"
