name: Production deploy

on:
  workflow_dispatch:

  push:
    branches:
      - cicd

  pull_request:

jobs:
  deploy:
    if: github.repository_owner == 'inno-sport-inh' && (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/cicd')
    name: Deploy to production server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            bash "${{ secrets.DEPLOY_SCRIPT }}"
