name: Tests
on: [push, workflow_dispatch]
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker compose -f deploy/docker-compose.test.yaml build --no-cache

      - name: Run app in docker
        run: docker compose -f deploy/docker-compose.test.yaml up -d --wait

      - name: Migrate auth
        run: |
          docker compose -f deploy/docker-compose.test.yaml exec -T adminpanel python manage.py makemigrations
          docker compose -f deploy/docker-compose.test.yaml exec -T adminpanel python manage.py migrate auth

      - name: Run tests
        run: docker compose -f deploy/docker-compose.test.yaml exec -T adminpanel pytest
